name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: yumata/lampa-source
          path: lampa-source

      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          path: lampa-source/.docker

      - name: Set up versioning
        id: vars
        run: |
          TAG=${GITHUB_SHA::7}
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=${DATE}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: lampa-source
          file: .docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: emergy/lampa:latest,emergy/lampa:${{ steps.vars.outputs.TAG }}
          build-args: |
            VERSION=${{ steps.vars.outputs.TAG }}
            BUILD_DATE=${{ steps.vars.outputs.BUILD_DATE }}
